name: "tags"
on: [push]

env:
  CURRENT_TAG: ${git describe --abbrev=0 --tags --always}

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Current Tag
      if: ${{ ${#env.CURRENT_TAG} > '15' }}
      run: echo ${{ env.CURRENT_TAG }}
    - name: First Tag
      if: ${{ ${#env.CURRENT_TAG} > '15' }}
      run: echo "1.0.1"
